version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{S3_BUCKETl}}"

phases:
  install:
    runtime-versions:
      nodejs: 23.10.0
    commands:
        - echo S3_BUCKET = $S3_BUCKET
        - echo Build started on `date`
        - echo Building the project...
        - npm cache clean --force
        - npm install -g @angular/cli@latest
        - npm install

  build:
    commands:
      - echo Build Started
      - ng build --configuration production --base-href /
      - echo Build completed on `date`      

artifacts:
  files:
    - '**/*'
  discard-paths: no

