version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{S3_BUCKETl}}"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 23.10.0
    commands:
        - echo S3_BUCKET = $S3_BUCKET
        - echo BUILD_FOLDER = $BUILD_FOLDER
        - echo Build started on `date`
        - echo Building the project...
        - npm cache clean --force
        - npm install -g @angular/cli@latest
        - npm install

  build:
    commands:
      - echo Build Started
      - ng build
      - echo Build completed on `date`      

artifacts:
  files:
    - '**/*'
  base-directory: './dist'
  discard-paths: no

